# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: refine.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crefine.proto\x12\x0fprompt_refinery\"A\n\rRefineRequest\x12\x17\n\x0foriginal_prompt\x18\x01 \x01(\t\x12\x17\n\x0frefinement_mode\x18\x02 \x01(\t\"\x86\x01\n\x0eRefineResponse\x12\x16\n\x0erefined_prompt\x18\x01 \x01(\t\x12\x17\n\x0fintent_detected\x18\x02 \x01(\t\x12\x16\n\x0eoriginal_score\x18\x03 \x01(\x05\x12\x15\n\rrefined_score\x18\x04 \x01(\x05\x12\x14\n\x0cimprovements\x18\x05 \x03(\t2`\n\rPromptRefiner\x12O\n\x0cRefinePrompt\x12\x1e.prompt_refinery.RefineRequest\x1a\x1f.prompt_refinery.RefineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'refine_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REFINEREQUEST']._serialized_start=33
  _globals['_REFINEREQUEST']._serialized_end=98
  _globals['_REFINERESPONSE']._serialized_start=101
  _globals['_REFINERESPONSE']._serialized_end=235
  _globals['_PROMPTREFINER']._serialized_start=237
  _globals['_PROMPTREFINER']._serialized_end=333
# @@protoc_insertion_point(module_scope)
