# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.services import refine_pb2 as refine__pb2


class PromptRefinerStub(object):
    """The gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RefinePrompt = channel.unary_unary(
                '/prompt_refinery.PromptRefiner/RefinePrompt',
                request_serializer=refine__pb2.RefineRequest.SerializeToString,
                response_deserializer=refine__pb2.RefineResponse.FromString,
                )


class PromptRefinerServicer(object):
    """The gRPC service definition
    """

    def RefinePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromptRefinerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RefinePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.RefinePrompt,
                    request_deserializer=refine__pb2.RefineRequest.FromString,
                    response_serializer=refine__pb2.RefineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prompt_refinery.PromptRefiner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PromptRefiner(object):
    """The gRPC service definition
    """

    @staticmethod
    def RefinePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/prompt_refinery.PromptRefiner/RefinePrompt',
            refine__pb2.RefineRequest.SerializeToString,
            refine__pb2.RefineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
